export const WEAPON_CATALOG = [
  { name: "Arm Strike", category: "armStrike", attackSkill: "armStrike", targetDefense: "parry", damageSkill: "muscle", damageDice: -1, accuracyModifier: 0, lethal: false, muscleRequirement: 0, damageType: "blunt", reach: "none", cost: "None", description: "Unarmed arm, hand, elbow, palm, or head-butt attack. Damage is Muscle -1d10, non-lethal, with no reach." },
  { name: "Axe", category: "mediumMelee", attackSkill: "mediumMelee", damageSkill: "muscle", damageDice: 1, damageType: "sharp", reach: "normal", cost: "430" },
  { name: "Battering Ram", category: "heavyMelee", attackSkill: "heavyMelee", damageSkill: "", damageDice: 1, damageType: "mighty", reach: "none", cost: "40", muscleRequirement: 1, qualities: "Damage is 1d10 per wielder." },
  { name: "Bian (Hard Whip)", category: "heavyMelee", attackSkill: "heavyMelee", damageSkill: "muscle", damageDice: 2, accuracyModifier: -1, damageType: "blunt", reach: "none", cost: "450", muscleRequirement: 2, qualities: "Aimed Strike Total Success stuns for one round. Attacks against objects use Open Damage." },
  { name: "Bow, Short", category: "smallRanged", attackSkill: "smallRanged", targetDefense: "evade", damageSkill: "", damageDice: 2, damageType: "sharp", reach: "normal", cost: "30", qualities: "Range 50/100/150 feet." },
  { name: "Bow, Composite", category: "smallRanged", attackSkill: "smallRanged", targetDefense: "evade", damageSkill: "", damageDice: 3, accuracyModifier: 1, damageType: "sharp", reach: "normal", cost: "100/500", muscleRequirement: 1, qualities: "Range 100/200/300 feet." },
  { name: "Butterfly Swords", category: "lightMelee", attackSkill: "lightMelee", damageSkill: "muscle", damageDice: 1, accuracyModifier: 1, parryBonus: 1, damageType: "sharp", reach: "none", cost: "425", qualities: "+1 Parry bonus." },
  { name: "Caltrops", category: "lightMelee", attackSkill: "lightMelee", damageSkill: "", damageDice: 0, lethal: false, damageType: "sharp", reach: "normal", cost: "10", qualities: "Can be scattered over a 10-foot area or thrown 15 feet. Direct throws take -1d10 Accuracy; multiple caltrops increase damage." },
  { name: "Catapults", category: "largeRanged", attackSkill: "largeRanged", targetDefense: "evade", damageSkill: "", damageDice: 6, accuracyModifier: -2, damageType: "mighty", reach: "normal", openDamage: true, cost: "4000", muscleRequirement: 2, qualities: "Range 100/300/600 feet." },
  { name: "Chain Whip", category: "mediumMelee", attackSkill: "mediumMelee", damageSkill: "speed", damageDice: 1, accuracyModifier: -1, damageType: "special", reach: "long", cost: "370", qualities: "Blunt or Sharp. Reach 10 feet / Long Reach." },
  { name: "Crossbow", category: "smallRanged", attackSkill: "smallRanged", targetDefense: "evade", damageSkill: "", damageDice: 2, accuracyModifier: 2, damageType: "sharp", reach: "normal", cost: "140/450", qualities: "Range 50/100/150 feet." },
  { name: "Dagger", category: "lightMelee", attackSkill: "lightMelee", damageSkill: "muscle", damageDice: 0, damageType: "sharp", reach: "none", cost: "75", qualities: "Can be thrown up to 15 feet." },
  { name: "Fan, Bamboo", category: "lightMelee", attackSkill: "lightMelee", damageSkill: "speed", damageDice: 0, accuracyModifier: 1, parryBonus: 1, damageType: "sharp", reach: "none", cost: "125", qualities: "+1 Parry bonus and +1 Stealth bonus for surprise attacks." },
  { name: "Fan, Metal", category: "lightMelee", attackSkill: "lightMelee", damageSkill: "speed", damageDice: 1, parryBonus: 1, damageType: "sharp", reach: "none", cost: "275", qualities: "+1 Parry bonus and +1 Stealth bonus for surprise attacks." },
  { name: "Fire Lance", category: "heavyMelee", attackSkill: "heavyMelee", damageSkill: "muscle", damageDice: 2, damageType: "special", reach: "long", cost: "700", muscleRequirement: 1, qualities: "Can also use Small Ranged at 20 feet for 3d10 Fire Damage, or 1d10 plus poison effect with a poisoned dart." },
  { name: "Fly-whisk (Chen Fu)", category: "lightMelee", attackSkill: "lightMelee", damageSkill: "speed", damageDice: 0, accuracyModifier: -1, lethal: false, damageType: "none", reach: "none", cost: "20", qualities: "Requires Expertise to use as a weapon. Can disarm." },
  { name: "Flying Guillotine", category: "mediumMelee", attackSkill: "mediumMelee", damageSkill: "", damageDice: 0, accuracyModifier: -3, damageType: "sharp", reach: "normal", cost: "Special", qualities: "Rumored weapon. Up to 20 feet; traps the target's head on a successful attack." },
  { name: "Guan Dao", category: "heavyMelee", attackSkill: "heavyMelee", damageSkill: "muscle", damageDice: 2, accuracyModifier: -1, damageType: "sharp", reach: "long", cost: "350", muscleRequirement: 2, qualities: "Reach 10 feet / Long Reach." },
  { name: "Gun (Staff), Dragon Long Pole", category: "mediumMelee", attackSkill: "mediumMelee", damageSkill: "muscle", damageDice: 0, damageType: "special", reach: "long", cost: "60", qualities: "Blunt and/or Sharp. Reach 15 feet / Long Reach." },
  { name: "Gun (Staff), Metal", category: "mediumMelee", attackSkill: "mediumMelee", damageSkill: "muscle", damageDice: 1, accuracyModifier: 1, damageType: "blunt", reach: "long", cost: "50", muscleRequirement: 1, qualities: "Reach 10 feet / Long Reach." },
  { name: "Gun (Staff), Wood", category: "mediumMelee", attackSkill: "mediumMelee", damageSkill: "muscle", damageDice: 0, accuracyModifier: 2, parryBonus: 1, lethal: false, damageType: "blunt", reach: "long", cost: "10", qualities: "+1 Parry bonus. Reach 10 feet / Long Reach." },
  { name: "Hook Sword", category: "mediumMelee", attackSkill: "mediumMelee", damageSkill: "muscle", damageDice: 0, accuracyModifier: 1, parryBonus: 1, damageType: "sharp", reach: "normal", cost: "375", qualities: "+1 Parry bonus. Can disarm. Total Success may knock target prone with failed TN 10 Athletics." },
  { name: "Iron Claw", category: "armStrike", attackSkill: "armStrike", damageSkill: "muscle", damageDice: 0, damageType: "sharp", reach: "none", cost: "10", qualities: "Total Success damage becomes Muscle +2d10." },
  { name: "Iron Hat", category: "lightMelee", attackSkill: "lightMelee", damageSkill: "reason", damageDice: 1, accuracyModifier: -1, parryBonus: 2, damageType: "sharp", reach: "normal", cost: "200", qualities: "May instead use Muscle +0d10. No Reach in melee or thrown 10 feet. +2 Parry. All 1s on attack damage the wielder." },
  { name: "Iron Thread", category: "lightMelee", attackSkill: "lightMelee", damageSkill: "muscle", damageDice: 1, damageType: "sharp", reach: "normal", cost: "100", qualities: "Up to 30 feet. Can restrain at distance. Counters against it suffer -1d10." },
  { name: "Ji (Halberd)", category: "heavyMelee", attackSkill: "heavyMelee", damageSkill: "muscle", damageDice: 3, accuracyModifier: -1, damageType: "mighty", reach: "long", cost: "275", muscleRequirement: 2 },
  { name: "Jian", category: "mediumMelee", attackSkill: "mediumMelee", damageSkill: "muscle", damageDice: 1, accuracyModifier: 2, damageType: "sharp", reach: "normal", cost: "500" },
  { name: "Kushen Sabre", category: "mediumMelee", attackSkill: "mediumMelee", damageSkill: "muscle", damageDice: 1, damageType: "sharp", reach: "normal", cost: "350" },
  { name: "Leg Strike", category: "legStrike", attackSkill: "legStrike", targetDefense: "parry", damageSkill: "muscle", damageDice: -1, lethal: false, damageType: "blunt", reach: "normal", cost: "None" },
  { name: "Mace, Giant", category: "heavyMelee", attackSkill: "heavyMelee", damageSkill: "muscle", damageDice: 4, accuracyModifier: -1, damageType: "blunt", reach: "normal", cost: "175", muscleRequirement: 3, qualities: "Requires Muscle-Lift Expertise. May exceed damage cap up to 7d10." },
  { name: "Meteor Hammer", category: "heavyMelee", attackSkill: "heavyMelee", damageSkill: "muscle", damageDice: 4, accuracyModifier: -2, damageType: "blunt", reach: "long", cost: "300", muscleRequirement: 3, qualities: "Requires Muscle-Lift Expertise. Reach 20 feet / Long Reach. Total Success may restrain or knock back 5 feet. May exceed damage cap up to 7d10." },
  { name: "Needle", category: "lightMelee", attackSkill: "lightMelee", damageSkill: "", damageDice: 0, lethal: false, damageType: "none", reach: "normal", cost: "5", qualities: "Thrown 5 feet. Good poison medium; multiple needles increase damage." },
  { name: "Net", category: "lightMelee", attackSkill: "lightMelee", damageSkill: "", damageDice: 0, accuracyModifier: -2, lethal: false, damageType: "none", reach: "normal", cost: "10", qualities: "No Damage. Successful attack removes two Moves and imposes -1d10 on all Physical/Combat Skills; Total Success removes three Moves." },
  { name: "Ox Tail Dao", category: "mediumMelee", attackSkill: "mediumMelee", damageSkill: "muscle", damageDice: 2, accuracyModifier: -1, damageType: "sharp", reach: "normal", cost: "400", muscleRequirement: 1, qualities: "Attack Total Success grants an Extra Wound instead of extra damage die." },
  { name: "Parasol", category: "lightMelee", attackSkill: "lightMelee", damageSkill: "muscle", damageDice: 1, evadeBonus: 2, damageType: "special", reach: "normal", cost: "75+", qualities: "Sharp and/or Blunt; lethal or non-lethal. Opened parasol grants +2 Evade against projectiles and +1d10 Athletics to reduce falling damage." },
  { name: "Qiang (Spear)", category: "heavyMelee", attackSkill: "heavyMelee", damageSkill: "muscle", damageDice: 2, damageType: "sharp", reach: "long", cost: "230", muscleRequirement: 1, qualities: "Reach 10 feet / Long Reach. One-handed use deals Muscle damage." },
  { name: "Rope Dart", category: "lightMelee", attackSkill: "lightMelee", damageSkill: "speed", damageDice: 2, accuracyModifier: -3, damageType: "sharp", reach: "long", cost: "200", muscleRequirement: 3, qualities: "Reach 20 feet / Long Reach. Accuracy penalty improves to -1d10 with 2+ Athletics ranks. Total Success may restrain or add 1 Extra Wound." },
  { name: "Sleeve Blade", category: "lightMelee", attackSkill: "lightMelee", damageSkill: "", damageDice: 1, parryBonus: 2, damageType: "sharp", reach: "none", cost: "450", qualities: "+2 Parry. Can add to Arm Strike Kung Fu Technique damage. -2d10 to skill rolls requiring holding other tools/weapons or hand-based Dianxue." },
  { name: "Spade of Sun Mai", category: "heavyMelee", attackSkill: "heavyMelee", damageSkill: "muscle", damageDice: 3, accuracyModifier: -1, damageType: "special", reach: "long", cost: "580", muscleRequirement: 1, qualities: "Mighty or Sharp." },
  { name: "Stick", category: "lightMelee", attackSkill: "lightMelee", damageSkill: "speed", damageDice: 0, accuracyModifier: 1, lethal: false, damageType: "blunt", reach: "normal", cost: "1" },
  { name: "Three Section Staff", category: "mediumMelee", attackSkill: "mediumMelee", damageSkill: "muscle", damageDice: 0, accuracyModifier: -1, parryBonus: 1, damageType: "blunt", reach: "long", cost: "175", qualities: "+1 Parry. Reach 15 feet / Long Reach. Total Success may restrain." },
  { name: "Thunderbolt Ball", category: "heavyMelee", attackSkill: "heavyMelee", targetDefense: "evade", damageSkill: "", damageDice: 5, accuracyModifier: -1, damageType: "mighty", reach: "normal", cost: "400", muscleRequirement: 2, qualities: "Thrown 15 feet plus 5 per Rank of Muscle. Explodes in 10-foot radius when attack roll exceeds targets' Evade." },
  { name: "Triple Bow Small Bed (Ballista)", category: "largeRanged", attackSkill: "largeRanged", targetDefense: "evade", damageSkill: "", damageDice: 6, damageType: "mighty", reach: "normal", cost: "2000", muscleRequirement: 2, qualities: "Range 200/400/800 feet." },
  { name: "Whirlwind Catapult", category: "largeRanged", attackSkill: "largeRanged", targetDefense: "evade", damageSkill: "", damageDice: 5, accuracyModifier: -1, damageType: "mighty", reach: "normal", openDamage: true, cost: "3000", muscleRequirement: 2, qualities: "Range 100/300/600 feet; 30-foot area." }
];

export const EQUIPMENT_CATEGORIES = {
  general: "General",
  clothing: "Clothing",
  tool: "Tool",
  foodDrink: "Food and Drink",
  instrument: "Musical Instrument",
  alchemical: "Alchemical",
  tradeGood: "Trade Good",
  service: "Service",
  mountTransport: "Mount or Transport",
  treasure: "Treasure"
};

export const MOUNT_TRANSPORT_CATALOG = [
  { name: "Barge", performanceRating: 6, handlingSpeed: "3 MPH / 1d10 (40 ft.)", milesPerDay: "40", speedScore: "6d10 (90 ft. / 18 hex)", evade: 5, hardiness: 5, integrity: 3, damage: "1d10", cost: "88,500" },
  { name: "Camel", performanceRating: 5, handlingSpeed: "30 MPH / 1d10 (40 ft.)", milesPerDay: "35", speedScore: "3d10 (60 ft. / 12 hex)", evade: 5, hardiness: 3, integrity: 1, damage: "0d10", cost: "1000" },
  { name: "Cart", performanceRating: 6, handlingSpeed: "30 MPH / 1d10 (40 ft.)", milesPerDay: "30", speedScore: "3d10 (60 ft. / 12 hex)", evade: 5, hardiness: 3, integrity: 1, damage: "0d10", cost: "200" },
  { name: "Elephant", performanceRating: 7, handlingSpeed: "25 MPH / 0d10 (30 ft.)", milesPerDay: "25", speedScore: "2d10 (50 ft. / 10 hex)", evade: 4, hardiness: 7, integrity: 4, damage: "5d10 or 1d10", cost: "15,000" },
  { name: "Horse", performanceRating: 4, handlingSpeed: "40 MPH / 3d10 (50 ft.)", milesPerDay: "40", speedScore: "5d10 (80 ft. / 16 hex)", evade: 6, hardiness: 4, integrity: 2, damage: "0d10", cost: "6000" },
  { name: "Imperial Steed", performanceRating: 3, handlingSpeed: "50 MPH / 4d10 (60 ft.)", milesPerDay: "50", speedScore: "6d10 (90 ft. / 18 hex)", evade: 6, hardiness: 5, integrity: 3, damage: "1d10", cost: "12,000" },
  { name: "Kushen Steed", performanceRating: 3, handlingSpeed: "60 MPH / 5d10 (70 ft.)", milesPerDay: "60", speedScore: "6d10 (90 ft. / 18 hex)", evade: 7, hardiness: 6, integrity: 3, damage: "1d10", cost: "15,000" },
  { name: "Junk, Imperial War", performanceRating: 8, handlingSpeed: "6 MPH / 2d10 (70 ft.)", milesPerDay: "100", speedScore: "4d10 (110 ft. / 22 hex)", evade: 5, hardiness: 9, integrity: 6, damage: "6d10", cost: "295,000" },
  { name: "Junk, Large War", performanceRating: 7, handlingSpeed: "8 MPH / 3d10 (100 ft.)", milesPerDay: "100", speedScore: "5d10 (160 ft. / 32 hex)", evade: 6, hardiness: 8, integrity: 5, damage: "5d10", cost: "177,000" },
  { name: "Junk, Merchant", performanceRating: 5, handlingSpeed: "6 MPH / 2d10 (80 ft.)", milesPerDay: "135", speedScore: "4d10 (120 ft. / 24 hex)", evade: 6, hardiness: 6, integrity: 3, damage: "2d10", cost: "106,200" },
  { name: "Junk, War", performanceRating: 6, handlingSpeed: "9 MPH / 4d10 (120 ft.)", milesPerDay: "100", speedScore: "6d10 (180 ft. / 36 hex)", evade: 7, hardiness: 7, integrity: 4, damage: "4d10", cost: "147,500" },
  { name: "Chariot", performanceRating: 7, handlingSpeed: "40 MPH / 3d10", milesPerDay: "40", speedScore: "5d10 (80 ft. / 16 hex)", evade: 5, hardiness: 5, integrity: 1, damage: "0d10", cost: "2,950" },
  { name: "Ox", performanceRating: 5, handlingSpeed: "30 MPH / 1d10 (40 ft.)", milesPerDay: "40", speedScore: "3d10 (60 ft. / 12 hex)", evade: 5, hardiness: 5, integrity: 3, damage: "2d10", cost: "1000" },
  { name: "Palanquin", performanceRating: 4, handlingSpeed: "9 MPH", milesPerDay: "10", speedScore: "2d10", evade: 3, hardiness: 3, integrity: 1, damage: "None", cost: "2000 to 150,000" }
];

export const GOODS_CATALOG = [
  { name: "Jade Wine (Chou jiu)", category: "foodDrink", cost: "", description: "Sticky-rice wine with a heavy white appearance. Traditional cup: white porcelain." },
  { name: "Pear Blossom Wine", category: "foodDrink", cost: "", description: "Sweet spring wine made when pear flowers bloom. Traditional cup: jade." },
  { name: "Snake Wine (She jiu)", category: "foodDrink", cost: "", description: "Rice wine infused with a snake. Lost Hardiness or Qi returns at twice the normal rate; at full Hardiness, one serving grants +1 Hardiness for one hour but inflicts 1d10 Damage. Traditional cup: wooden horn." },
  { name: "Sorghum Wine (Kaoliang)", category: "foodDrink", cost: "", description: "Strong alcohol brewed from sorghum. Traditional cup: bronze." },
  { name: "Yellow Wine (Huang jiu)", category: "foodDrink", cost: "", description: "Grain-based wine, usually rice-based, with several color and ingredient subtypes. Traditional cup: blue porcelain." },
  { name: "Erhu", category: "instrument", cost: "", description: "Two-stringed bowed fiddle with a tall neck and eight-sided body, often covered with snakeskin." },
  { name: "Guzheng", category: "instrument", cost: "", description: "Large horizontal zither with up to 21 strings, prized for an elegant water-like sound." },
  { name: "Guqin", category: "instrument", cost: "", description: "Seven-string zither regarded as an elegant instrument." },
  { name: "Horse Headed Fiddle", category: "instrument", cost: "", description: "Two-string fiddle popular among the Kushen and Kailin, with a large square body." },
  { name: "Pipa (Lute)", category: "instrument", cost: "", description: "Pear-shaped four-string lute held in the lap and plucked." },
  { name: "Divine Fire", category: "alchemical", cost: "800 per duo", description: "Combustible powder used in firelances or fireworks. One pound creates a 10-foot explosion dealing 3d10 Open Damage; each additional pound adds 10 feet of radius. Trade (Alchemy) TN 9." },
  { name: "Smoke Powder", category: "alchemical", cost: "500 per duo", description: "Ignited smoke powder fills a 20-foot radius with Lights-out illumination for 1d10 rounds. Trade (Alchemy) TN 7." },
  { name: "Paints and Inks", category: "alchemical", cost: "Varies", description: "Writing and art substances of varied quality and color. General creation TN 6." },
  { name: "Gecko Cinnabar", category: "tradeGood", cost: "800 per ounce" },
  { name: "Gold", category: "tradeGood", cost: "10,000 per ounce" },
  { name: "Rice", category: "tradeGood", cost: "50 for 1 Duo (6.6 liters)" },
  { name: "Salt", category: "tradeGood", cost: "60 per pound" },
  { name: "Silk", category: "tradeGood", cost: "2,000 per bolt" },
  { name: "Silver", category: "tradeGood", cost: "1,000 per ounce" },
  { name: "Blanket", category: "general", cost: "50-2,100" },
  { name: "Calligraphy Brush", category: "tool", cost: "12-4,000" },
  { name: "Cauldron", category: "tool", cost: "400" },
  { name: "Cricket", category: "general", cost: "4" },
  { name: "Cricket (Champion)", category: "general", cost: "5,000" },
  { name: "Cup, Porcelain", category: "general", cost: "10" },
  { name: "Ink Stick", category: "tool", cost: "15" },
  { name: "Ink Stone", category: "tool", cost: "25" },
  { name: "Lantern, Glass", category: "tool", cost: "300" },
  { name: "Lantern, Paper or Silk", category: "tool", cost: "100" },
  { name: "Lantern, Palace", category: "tool", cost: "8,000" },
  { name: "Lantern, Shadow Picture", category: "tool", cost: "1,000" },
  { name: "Lantern, Sky", category: "tool", cost: "150" },
  { name: "Lover's Bao (Perfumed Satchel)", category: "general", cost: "50 - 1,000" },
  { name: "Make-up", category: "general", cost: "160 - 3,000" },
  { name: "Mirror", category: "general", cost: "200 - 3,400" },
  { name: "Mortar and Pestle", category: "tool", cost: "60" },
  { name: "Pet Cat", category: "general", cost: "500" },
  { name: "Pet Cormorant (Fishing Bird)", category: "general", cost: "900" },
  { name: "Pet Dog", category: "general", cost: "650" },
  { name: "Pet Fancy Tail Carp", category: "general", cost: "200" },
  { name: "Torch", category: "tool", cost: "10" },
  { name: "Xi Pottery", category: "general", cost: "400" },
  { name: "Xuan Paper", category: "tool", cost: "10" },
  { name: "Cap (Jin)", category: "clothing", cost: "10" },
  { name: "Conical Hat (Duoli)", category: "clothing", cost: "8" },
  { name: "Hai'an Hat (Gaoshan Guan)", category: "clothing", cost: "1,000" },
  { name: "Hat (Guan)", category: "clothing", cost: "100 - 2,000" },
  { name: "Hat, Gugu", category: "clothing", cost: "400" },
  { name: "Headcloth (Zi Man)", category: "clothing", cost: "5" },
  { name: "Headcloth, Ornamental (Lei Jin)", category: "clothing", cost: "20" },
  { name: "Mian (Lacquer Board with Jade Beads)", category: "clothing", cost: "14,000 - 75,000" },
  { name: "Phoenix Crown (Feng Guan)", category: "clothing", cost: "2,000+" },
  { name: "Winged Official Hat, Zhan Dao (Fotou)", category: "clothing", cost: "200" },
  { name: "Belt, Ornate", category: "clothing", cost: "150" },
  { name: "Belt, Simple", category: "clothing", cost: "40" },
  { name: "Boots (pair)", category: "clothing", cost: "80" },
  { name: "Cloud Collar (Xiapei)", category: "clothing", cost: "300" },
  { name: "Coat, Open (Beizi), Cotton", category: "clothing", cost: "100" },
  { name: "Coat, Open (Beizi), Silk", category: "clothing", cost: "300" },
  { name: "Dragon Robe, Imperial (Longpao)", category: "clothing", cost: "20,000" },
  { name: "Gown, Cotton", category: "clothing", cost: "235" },
  { name: "Gown, Silk", category: "clothing", cost: "470" },
  { name: "Jacket, Closed, Cotton", category: "clothing", cost: "250" },
  { name: "Jacket, Closed, Silk", category: "clothing", cost: "500" },
  { name: "Python Robe, Official (Mangpao)", category: "clothing", cost: "3,000" },
  { name: "Sandals (Pair)", category: "clothing", cost: "25" },
  { name: "Sash", category: "clothing", cost: "45" },
  { name: "Scarf, Cotton", category: "clothing", cost: "22" },
  { name: "Scarf, Silk", category: "clothing", cost: "45" },
  { name: "Seven Star Shawl", category: "clothing", cost: "500" },
  { name: "Shoes (pair)", category: "clothing", cost: "45" },
  { name: "Trousers, Cotton", category: "clothing", cost: "80" },
  { name: "Trousers, Silk", category: "clothing", cost: "160" },
  { name: "Tunic, Silk", category: "clothing", cost: "200" },
  { name: "Tunic, Cotton", category: "clothing", cost: "100" },
  { name: "Wrap Coat, Cotton", category: "clothing", cost: "222" },
  { name: "Wrap Coat, Silk", category: "clothing", cost: "445" },
  { name: "Wrap Robe, Cotton", category: "clothing", cost: "170" },
  { name: "Wrap Robe, Silk", category: "clothing", cost: "340" },
  { name: "Wrap Skirt and Blouse (Ruqun), Cotton", category: "clothing", cost: "100" },
  { name: "Wrap Skirt and Blouse (Ruqun), Silk", category: "clothing", cost: "200" },
  { name: "Very Luxurious Clothing Ornamentation", category: "clothing", cost: "Add +2,000-8,000" },
  { name: "Shadow Puppet, Average", category: "general", cost: "80" },
  { name: "Shadow Puppet, Mid-Quality", category: "general", cost: "400" },
  { name: "Shadow Puppet, Very Fine Quality", category: "general", cost: "3,000" },
  { name: "Armed Escort", category: "service", cost: "20/day per armed guard" },
  { name: "Armed Escort (Martial Hero Qi Rank 1)", category: "service", cost: "200/day" },
  { name: "Armed Escort (Martial Hero Qi Rank 2)", category: "service", cost: "400/day" },
  { name: "Armed Escort (Martial Hero Qi Rank 3)", category: "service", cost: "800/day" },
  { name: "Fortune Teller", category: "service", cost: "10 per reading" },
  { name: "Guide", category: "service", cost: "20/day per Rank in Survival (+20 for relevant expertise)" },
  { name: "Inn Room (Cheap)", category: "service", cost: "10" },
  { name: "Inn Room (Mid-Quality)", category: "service", cost: "100" },
  { name: "Inn Room (Very Luxurious)", category: "service", cost: "1000" },
  { name: "Meal, Cheap (Restaurant)", category: "service", cost: "5" },
  { name: "Meal, Mid-Quality (Restaurant)", category: "service", cost: "50 - 200" },
  { name: "Meal, Very Luxurious", category: "service", cost: "1,000+" },
  { name: "Musician", category: "service", cost: "3 per song" },
  { name: "Physician", category: "service", cost: "100 per day of care" },
  { name: "Singer", category: "service", cost: "5 per song" },
  { name: "School Entrance Fee", category: "service", cost: "1,000 to 4,000" }
];
